---
# tasks file for roles/deploy
- debug: var=jenkins_job_name

- name: Create deployment info dir
  file:
    path: /var/lib/tomcat/webapps/
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"
  become: yes
  become_method: sudo



- name: Put deployment info file
  template:
    src: 'deploy-info.txt.j2d'
    mode: "u=rwx,g=rwx,o=rwx"
    dest: /var/lib/tomcat/webapps/deploy-info.txt
  become: yes
  become_method: sudo

- name:
  deployment: url="{{ url }}" war="{{ war }}" username="{{ username }}" password="{{ password }}"
  delegate_to: localhost







