---

- hosts: localhost
  tasks:
    - name: Vagrant status
      vagrant:
        dest: /home/student/cm/ansible/day-4/
        state: started
      register: hostinfo

    - name: Jenkins vars lookup
      command: echo "{{ lookup('env','WORKSPACE') }}"
      register: jenkins_job_workspace

    - debug: var=jenkins_job_workspace

    - name: Add discovered hosts
      add_host:
        groups: vagrant
        name: "{{ hostinfo.os_name }}"
        hostname: "{{ hostinfo.os_name }}"
        ansible_host: "{{ hostinfo.ip }}"
        ansible_port: "{{ hostinfo.port }}"
        ansible_connection: ssh
        ansible_user: "{{ hostinfo.user }}"
        ansible_ssh_private_key_file: "{{ hostinfo.key }}"
      when: hostinfo.status == "running"
  tags: create

- name: Tomcat provision
  hosts: vagrant
  become: yes
  become_method: sudo
  roles:
  - java
  - tomcat
  - nginx
  tags: provision

- name: App deployment
  hosts: vagrant
  roles:
  - deploy
  tags: deployment

- name: TESTING
  hosts: vagrant
  roles:
    - java_test
    - tomcat_test
    - nginx_test
  tags: testing
