---
# tasks file for roles/nginx_test
- name: check nginx is running
  shell: service nginx status
  become: yes

- name: Check for nginx web page
  uri:
    url: "http://{{nginx_address}}:{{nginx_port}}"
    return_content: yes
  register: webpage

