---
# tasks file for roles/nginx_test
- name: check nginx is running
  shell: service nginx status
  become: yes

#- name: Perform a HEAD on nginx
#  uri:
#    uri: http://{{nginx_address}}:{{nginx_port}}
#    method: HEAD


- name: nginx is listening on port 80
  wait_for:
    host: 192.168.56.13
    port: 80
    delay: 10
    state: started
  delegate_to: localhost

