---
# tasks file for roles/nginx_test
- name: check nginx is running
  shell: service nginx status
  become: yes

- shell: |
    res=`/sbin/service nginx status | grep 'is running'`
    if [[ $res != '' ]]; then echo STARTED; fi
  register: result

- name: debug
  debug:
    msg: "nginx status: {{result.stdout}}"
