---
# tasks file for roles/java_test
- name: show java version
  shell: java -version
  register: result

- name: Check for output of Java
  shell: java -version
  register: output
- debug: var=output.stderr_lines